[package]
name = "r3y-faces-example"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["fs", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
image = "0.24.9"
imageproc = "0.23.0"
rustface = { version = "0.1.7", default-features = false }
indicatif = {version = "0.18.6"}
clap = { version = "4.5.0", features = ["derive"] }
